### ISSUE TITLE
A few minor things to clean up

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/buried-water-electrostatics#1]
1) README.md formatting and details. Note that these use Markdown format, which is actually pretty nice and allows you to create headers, subheaders, etc. A couple specific things to address:
a) Make the README.md begin with a title rather than "buried-water-electrostatics".
b) Give a reference to the water asymmetry paper which motivated this (note the linking syntax for markdown). 
c) Break your README.md up just slightly into a subsection at the top which explains what we were trying to do, then a lower subsection which explains how to reproduce it. Right now, you get to how exactly to do it before you've exactly said WHAT is done here. What I mean is, you might want a bit saying something like, "and found none. Specifically, we built a list of X,XXX high resolution protein structures meeting certain criteria, extracted the locations of all water molecules, evaluated the electrostatic potential at the location of every water molecule, and then made a histogram of the resulting potentials (which is shown here in `fileXYZ.pdf`). Here is the code to reproduce..." 
d) Please state WHICH version of the OpenEye software you used.

2) Code cleanup in `Buried_Water_Potentials.py` and related (e.g. `README.md`) -- `f` is just a bad name for a function, because it doesn't say anything about what it does. Could you change the name to something which expresses an action, then use this in your `README.md` and in your code elsewhere? (Note this also gets confusing even in `Buried_Water_Potentials.py` as you have a function `f` AND a file `f`. Also, can you please make the function have a doc string, even a very brief one, which explains what it does and what the arguments are? (Right now one can't know what the function is supposed to take in from reading it). Here's an example of the style we usually try to follow for doc strings: https://github.com/open-forcefield-group/smarty/blob/master/smarty/forcefield.py#L134

3)  You remove PDB files which resulted in an IndexError. Do you have a list of these/can you build one and deposit? (I'd like the full list of PDBs successfully processes, as well as a graph of the final results -- plus the actual data if it is not too large -- deposited on here.)

4) What about analysis scripts? Presumably you had something which took all of this analysis and processed/graphed? It would be good to have the analysis on here as well.

Can you resolve via a pull request (or multiple pull requests), @davidwych ?

**Comment by davidlmobley** [comment]
@davidwych - I think you've got most of this, but 3 and 4 require attention still I think.

If you have the time, I'd like to wrap this up today or at least in the next couple of days. Once everything is final, I'll actually do a "release" of the project, which will also result in it the particular release getting assigned a permanent DOI via Zenodo. That's sort of handy, as it makes it cite-able and sort of formalizes it.

**Comment by davidwych** [comment]
I believe all of your issues have been addressed now, but please let me know if there's anything more I can do.
